// <auto-generated />
namespace KPSZI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class upd_after_add_SFHMeasures_dependencies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upd_after_add_SFHMeasures_dependencies));
        
        string IMigrationMetadata.Id
        {
            get { return "201805180415017_upd_after_add_SFH-Measures_dependencies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
