// <auto-generated />
namespace KPSZI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addtoSFHTypekorolev : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtoSFHTypekorolev));
        
        string IMigrationMetadata.Id
        {
            get { return "201804090354542_add-to-SFHType-korolev"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
